theme = "x"
baseURL = "https://xuchengpeng.github.io/hugo-x"
defaultContentLanguage = "en"

enableRobotsTXT = true
summaryLength = 0
hasCJKLanguage = true
enableEmoji = true

buildDrafts = false
buildFuture = false

[pagination]
  pagerSize = 10

[taxonomies]
  tag = "tags"
  category = "categories"

[outputs]
  home = ["HTML", "RSS", "JSON"]
