theme = "x"
baseURL = "https://xuchengpeng.cn"
defaultContentLanguage = "en"

enableRobotsTXT = true
summaryLength = 0
hasCJKLanguage = true
enableEmoji = true

buildDrafts = false
buildFuture = false

[pagination]
  pagerSize = 15

[taxonomies]
  tag = "tags"
  category = "categories"

[outputs]
  home = ["HTML", "RSS", "JSON"]
