[[main]]
  name = "Posts"
  pageRef = "posts"
  weight = 10
[[main]]
  name = "Projects"
  pageRef = "projects"
  weight = 20
[[main]]
  name = "About"
  pageRef = "about"
  weight = 30

[[footer]]
  name = "Tags"
  pageRef = "tags"
  weight = 10
[[footer]]
  name = "Categories"
  pageRef = "categories"
  weight = 20
