defaultTheme = "light" # light, dark
mainSections = ["posts"]
showRecentItems = 9

[article]
  showBreadcrumbs = true
  showMeta = true
  showTags = true
  showMath = false
  showToc = true
  showPagination = true
  showSummary = false
