defaultTheme = "light" # light, dark
mainSections = ["posts", "notes"]
showRecentItems = 5

[article]
  showBreadcrumbs = true
  showMeta = true
  showTags = true
  showMath = false
  showToc = true
  showPagination = true
