disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "Chuck"

[params]
  description = "A powerful, lightweight theme for Hugo."
  dateFormat = "2 January 2006"

[params.author]
  name = "Chuck"
  email = "chuckxcp@qq.com"