defaultMarkdownHandler = 'goldmark'

[goldmark]
[goldmark.renderer]
  unsafe = true
[goldmark.parser.attribute]
  title = true

[highlight]
  noClasses = false

[tableOfContents]
  startLevel = 2
  endLevel = 4
