defaultTheme = "light" # light, dark
mainSections = ["posts"]
showRecentItems = 5
# robots = ""
# keywords = [""]

[article]
  showBreadcrumbs = true
  showMeta = true
  showTags = true
  showMath = false
  showToc = true
  showPagination = true
